# -*- coding: utf-8 -*-
"""MoodifyMentalHealthAnalysisSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1izjobBt4Mvm1c__RQsLRYAi0PKgVKWFp
"""

import numpy as np
import pandas as pd
import pickle

data=pd.read_csv('DatasetMentalDisordersnew.csv')

x=data.drop('Expert Diag0se',axis=1)
y=data['Expert Diag0se']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train, y_train)

pickle.dump(model, open('mentalhealth.pkl', 'wb'))

