# -*- coding: utf-8 -*-
"""MoodifySongRecommendationSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DbcwrMNOz795dmygv6MxsdcI1JZUActI
"""

import numpy as np
import pandas as pd
import pickle

data = pd.read_csv('music.csv')
x=data.drop('Fav song',axis=1)
y=data['Fav song']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train, y_train)

pickle.dump(model, open('songrecc.pkl', 'wb'))

